import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";
import { lanUrlsPlugin } from "./scripts/lan-urls.ts";
import { relayPlugin } from "./scripts/relay-plugin.ts";
import { traceEndpoint } from "./scripts/trace-endpoint.ts";

const fromRoot = (path: string) =>
	fileURLToPath(new URL(path, import.meta.url));

/** Single source of truth for the port, shared with scripts/setup-certs.ts. */
const PORT: number = JSON.parse(
	readFileSync(fromRoot("./package.json"), "utf8"),
).config.port;

/**
 * iOS refuses DeviceMotion outside a secure context, so the dev server has to
 * speak HTTPS to be testable on a real phone. Certificates are generated by
 * `npm run certs` into ./certs, which is gitignored.
 *
 * Falling back to HTTP rather than failing is deliberate: unit tests, the host
 * page and the lobby UI are all workable over plain HTTP, and only the motion
 * input actually needs TLS.
 *
 * See llm-knowledge/decisions/0004-lan-https-via-local-ip-co.md
 */
function devServerHttps() {
	const key = fromRoot("./certs/key.pem");
	const cert = fromRoot("./certs/cert.pem");
	if (!existsSync(key) || !existsSync(cert)) {
		console.warn(
			"\n[couchcourt] No certificates in ./certs — serving over HTTP.\n" +
				"[couchcourt] iOS will refuse motion sensors. Run `npm run certs` first.\n",
		);
		return undefined;
	}
	return { key: readFileSync(key), cert: readFileSync(cert) };
}

export default defineConfig(({ command, mode, isPreview }) => {
	// Only when actually serving a browser. As a module-level constant this also
	// warned during `vite build` and `vitest`, which put "iOS will refuse motion
	// sensors" into every CI log — advice both useless and untrue there.
	// Vitest runs as command "serve" with mode "test", hence both checks.
	// `vite preview` is a third "serve" — it is the production server
	// (decision 0010), so it wants TLS but not the recorder.
	const serving = command === "serve" && mode !== "test";
	const https = serving ? devServerHttps() : undefined;

	return {
		appType: "mpa",
		// Root at src/ so the build emits dist/host/ and dist/controller/ rather
		// than burying both pages under dist/src/.
		root: fromRoot("./src"),
		// Gated on `serving`, not on the plugin's own `apply: "serve"` alone:
		// Vitest also runs as command "serve" (with mode "test"), which is
		// exactly the case `serving` exists to exclude. Without this gate a
		// filesystem-writing endpoint would come alive on every `vitest run`.
		// The relay and the printed URLs belong to both serve-time servers (dev
		// and preview); the recorder writes to the repo's fixture folder and
		// belongs only to dev.
		plugins: serving
			? [
					...(isPreview
						? []
						: [traceEndpoint(fromRoot("./tests/fixtures/motion"))]),
					relayPlugin(),
					lanUrlsPlugin(),
				]
			: [],
		build: {
			outDir: fromRoot("./dist"),
			emptyOutDir: true,
			// The host bundle is ~665 kB and three.js is 543 kB of it, so no
			// split gets under Vite's default 500 kB (measured 2026-09-25 with a
			// `three` manualChunk). It is fetched once, over the LAN, from the
			// laptop it runs on. The limit sits just above today's size so the
			// warning still means "this grew".
			chunkSizeWarningLimit: 700,
			rollupOptions: {
				// Three pages, one build: the redirect, the court, and the racket.
				input: {
					// `/` is a redirect to the host page, so a Mac that opens the
					// bare LAN address lands somewhere.
					index: fromRoot("./src/index.html"),
					host: fromRoot("./src/host/index.html"),
					controller: fromRoot("./src/controller/index.html"),
				},
			},
		},
		server: {
			port: PORT,
			// Guests reach this from their phones, so it must not bind to localhost.
			host: true,
			// Spread rather than assign: exactOptionalPropertyTypes forbids an
			// explicit `https: undefined`.
			...(https ? { https } : {}),
		},
		// `npm start` — same port, same certificates, same relay, serving the
		// built pages instead of the source ones.
		preview: {
			port: PORT,
			host: true,
			...(https ? { https } : {}),
		},
		test: {
			// No jsdom: everything worth testing is either pure or server-side.
			environment: "node",
			// Relative to the repo, not to `root` above.
			root: fromRoot("."),
			include: [
				"src/**/*.test.ts",
				"scripts/**/*.test.ts",
				"tests/**/*.test.ts",
			],
		},
	};
});
