import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

const fromRoot = (path: string) =>
	fileURLToPath(new URL(path, import.meta.url));

/** Single source of truth for the port, shared with scripts/setup-certs.mjs. */
const PORT: number = JSON.parse(
	readFileSync(fromRoot("./package.json"), "utf8"),
).config.port;

/**
 * iOS refuses DeviceMotion outside a secure context, so the dev server has to
 * speak HTTPS to be testable on a real phone. Certificates are generated by
 * `npm run certs` into ./certs, which is gitignored.
 *
 * Falling back to HTTP rather than failing is deliberate: unit tests, the host
 * page and the lobby UI are all workable over plain HTTP, and only the motion
 * input actually needs TLS.
 *
 * See llm-knowledge/decisions/0004-lan-https-via-local-ip-co.md
 */
function devServerHttps() {
	const key = fromRoot("./certs/key.pem");
	const cert = fromRoot("./certs/cert.pem");
	if (!existsSync(key) || !existsSync(cert)) {
		console.warn(
			"\n[swingcourt] No certificates in ./certs — serving over HTTP.\n" +
				"[swingcourt] iOS will refuse motion sensors. Run `npm run certs` first.\n",
		);
		return undefined;
	}
	return { key: readFileSync(key), cert: readFileSync(cert) };
}

export default defineConfig(({ command, mode }) => {
	// Only when actually serving a browser. As a module-level constant this also
	// warned during `vite build` and `vitest`, which put "iOS will refuse motion
	// sensors" into every CI log — advice both useless and untrue there.
	// Vitest runs as command "serve" with mode "test", hence both checks.
	const serving = command === "serve" && mode !== "test";
	const https = serving ? devServerHttps() : undefined;

	return {
		appType: "mpa",
		// Root at src/ so the build emits dist/host/ and dist/controller/ rather
		// than burying both pages under dist/src/.
		root: fromRoot("./src"),
		build: {
			outDir: fromRoot("./dist"),
			emptyOutDir: true,
			rollupOptions: {
				// Two pages, one build. The host renders the court; the phone is a racket.
				input: {
					host: fromRoot("./src/host/index.html"),
					controller: fromRoot("./src/controller/index.html"),
				},
			},
		},
		server: {
			port: PORT,
			// Guests reach this from their phones, so it must not bind to localhost.
			host: true,
			// Spread rather than assign: exactOptionalPropertyTypes forbids an
			// explicit `https: undefined`.
			...(https ? { https } : {}),
		},
		// NOTE: once src/server exists, attach the WebSocket server to Vite's own
		// httpServer with a small plugin (configureServer hook) rather than running
		// a second process. Dev and production then share one port and one code
		// path. See llm-knowledge/decisions/0002-host-authoritative-simulation.md
		test: {
			// No jsdom: everything worth testing is either pure or server-side.
			environment: "node",
			// Relative to the repo, not to `root` above.
			root: fromRoot("."),
			include: ["src/**/*.test.ts", "tests/**/*.test.ts"],
		},
	};
});
